### ISSUE TITLE
More detail about PC <-> Duino protocol

### ISSUE THREAD

**Issue by iDoka** [atlas0fd00m/CanCat#7]
Could you share more documentation of these protocol:
```
// PC->Duino:  <size><cmd><data>  where size includes cmd and data but not the size byte itself
// Duino->PC:  @<size><cmd><data> where size includes cmd and data
```
?

I suppose the protocol based on existed and well documented. What name of CAN-over-UART protocol do you use in CANcat?
That's not similar to widely used lawicel ASCII CAN protocol. Unfortunately.

**Comment by atlas0fd00m** [comment]
what you see is what you get.  it's clearly documented in code. :)
no, seriously.  it's just a basic, easily extensible, binary command and control protocol.  we're moving more and more toward a required Request->Response pair where the client sends a request and the firmware replies with some sort of response.  the opposite is not true, as the firmware can push log messages, CAN messages, etc... without the client needing to respond.  it simply accepts it and stores it in the proper "mailbox" or handles it directly (in the case of log messages).

hopefully that helps.

no, we avoid LAWICEL at the moment, because we don't want to use an ASCII protocol.  it's wasteful.  our binary protocol is far more efficient.
however, at some future time we may implement LAWICEL as an option.  it's just not been worth the time and effort so far.

**Comment by iDoka** [comment]
ASCII-based protocols not so ugly as you imagine (like AT-command in GSM, ELM327 protocol, Bluetooth config UART protocol, etc).
The overhead of ASCII not so critical (1Mbit CAN vs 12Mbit USB FullSpeed), but offer more advantages:
- Human readable (for analyze, debug and interactive session)
- Reliability: unique SOF and EOF marker for self-recoverable incoming frame parser
- Compatibility with linux CAN-stack (SocketCAN with slcan driver) and more Windows program (like CANhacker)

**Comment by iDoka** [comment]
That's easy to add based on many implementation sources, e.g.:
https://github.com/autowp/arduino-canhacker
